workspace(name = "knightwu_project")

# https://github.com/bazelbuild/bazel-skylib/releases/download/1.1.1/bazel-skylib-1.1.1.tar.gz
local_repository(
    name = "bazel_skylib",
    path = "/home/knightwu/projects/third/bazel-skylib",
)

# https://github.com/protocolbuffers/protobuf/archive/v3.16.0.tar.gz
local_repository(
    name = "com_google_protobuf",
    path = "/home/knightwu/projects/third/protobuf3",
)

# https://github.com/google/googletest/archive/refs/tags/release-1.12.1.zip
local_repository(
    name = "com_google_googletest",
    path = "/home/knightwu/projects/third/googletest",
)

# https://github.com/grpc/grpc/archive/refs/tags/v1.47.1.tar.gz
local_repository(
    name = "com_github_grpc_grpc",
    path = "/home/knightwu/projects/third/grpc",
)

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")
protobuf_deps()

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")
bazel_skylib_workspace()

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()
load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")
grpc_extra_deps()
